@baseUrl = http://localhost:5064
@contentType = application/json

### Register a new user
POST {{baseUrl}}/api/auth/register
Content-Type: {{contentType}}

{
    "username": "testuser",
    "password": "TestPassword123!"
}